### ISSUE TITLE
Errors after updating to V3 and missed detections

### ISSUE THREAD

**Issue by backslashV** [NickM-27/swatch-hass-integration#10]
Hi,
After updating to v3, I see the following in the HA logs:
```
Unexpected error fetching swatch data:
Traceback (most recent call last):
  File "/config/custom_components/swatch/api.py", line 98, in api_wrapper
    response = await self._session.get(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1050, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 961, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 499, in sock_connect
    return await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/swatch/api.py", line 115, in api_wrapper
    return await response.json()
  File "/usr/local/lib/python3.9/site-packages/async_timeout/__init__.py", line 129, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.9/site-packages/async_timeout/__init__.py", line 212, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 191, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/swatch/__init__.py", line 170, in _async_update_data
    raise exc
  File "/config/custom_components/swatch/__init__.py", line 168, in _async_update_data
    return await self._api.async_get_object_state("all")
  File "/config/custom_components/swatch/api.py", line 76, in async_get_object_state
    await self.api_wrapper(
  File "/config/custom_components/swatch/api.py", line 123, in api_wrapper
    raise SwatchApiClientError from exc
custom_components.swatch.api.SwatchApiClientError
```
```
Some error occurred
```

Also, detections are now returning _result: false_ even though the area is within the values defined in the config. These are the same images that were being detected prior to v3 update.

Addon version: 3.0.2
Integration version: 1.1.1

**Comment by NickM-27** [comment]
Thanks I'll look into that, haven't seen any integration errors myself so may need to get the config.

> Also, detections are now returning result: false even though the area is within the values defined in the config. These are the same images that were being detected prior to v3 update.

I would recommend trying to reduce the min and increase the max area size just to see. Instead of counting "all matching pixels" I now find clusters of matching pixels and calcualte a bounding box, it uses the area of this box so that area may have changed some. If that still doesn't help then I'd likely need the image and color value so I can manually test

**Comment by backslashV** [comment]
Thanks. Lowering those values worked.

**Comment by NickM-27** [comment]
Sorry for the lack of communication on that, but I am hoping this new system will make it a lot easier to get consistent readings since stray pixels in the image that match won't add to the possibility of a false positive

**Comment by NickM-27** [comment]
Looking closer this appears to be `asyncio.exceptions.TimeoutError`. Did this happen often? I'm not sure if there is something inside the integration that would be responsible for this.

**Comment by backslashV** [comment]
So far it's happened about 100 times since yesterday according to the HA logs. I have an automation that calls the swatch service every 5 minutes.

**Comment by NickM-27** [comment]
I see, that is helpful, thanks!
