### ISSUE TITLE
[FEATURE REQUEST] Ability to upload local images through swatch service

### ISSUE THREAD

**Issue by backslashV** [NickM-27/swatch-hass-integration#8]
Hi,
I was wondering if you can add support for internal paths like /config/dir for the Swatch service image_url parameter.

**Comment by NickM-27** [comment]
I'll probably just add a second parameter, but yeah I believe that should be doable

**Comment by NickM-27** [comment]
It looks like a direct path in HomeAssistant is not allowed as the integrations don't have direct access to the file structure. But passing something like `media-source://media_source/local/audio/doorbell.mp3` like how the media player does it should already work. Will keep digging to see if this is possible.

**Comment by backslashV** [comment]
> It looks like a direct path in HomeAssistant is not allowed as the integrations don't have direct access to the file structure. But passing something like `media-source://media_source/local/audio/doorbell.mp3` like how the media player does it should already work. Will keep digging to see if this is possible.

Is this the /media folder? /local usually means the /config/www folder which is unsafe for storing anything sensitive since it's accessible w/o authentication. The /config/www folder can be used in the form of a URL for image_url if that's what you meant.

**Comment by NickM-27** [comment]
It's the /media and I added /local/audio. It's not the www folder. Main point is I'm not sure the integration has access to the file system directly and may be required to use a url like that. Will have to see for sure though

**Comment by backslashV** [comment]
So I tried with various forms and they all resulted in one sort of error:
I have a file in the /media dir called black.jpg

```
service: swatch.detect_object
data:
  image_url: media-source://media_source/black.jpg
target:
  entity_id: binary_sensor.door_stop_sign


ERROR:swatch.http:Exception on /api/garage_cam/detect [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/opt/swatch/swatch/http.py", line 81, in detect_camera_frame
    result: Dict[str, Any] = current_app.image_processor.detect(camera_name, image_url)  # type: ignore[attr-defined]
  File "/opt/swatch/swatch/image.py", line 77, in detect
    imgBytes = requests.get(image_url).content
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 639, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 732, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for 'media-source://media_source/black.jpg'
```


```
service: swatch.detect_object
data:
  image_url: /media/black.jpg
target:
  entity_id: binary_sensor.door_stop_sign


ERROR:swatch.http:Exception on /api/garage_cam/detect [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/opt/swatch/swatch/http.py", line 81, in detect_camera_frame
    result: Dict[str, Any] = current_app.image_processor.detect(camera_name, image_url)  # type: ignore[attr-defined]
  File "/opt/swatch/swatch/image.py", line 77, in detect
    imgBytes = requests.get(image_url).content
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 515, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 443, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 318, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 392, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/media/black.jpg': No scheme supplied. Perhaps you meant http:///media/black.jpg?
```


```
service: swatch.detect_object
data:
  image_url: <HA IP>/media/black.jpg
target:
  entity_id: binary_sensor.door_stop_sign

ERROR:swatch.http:Exception on /api/garage_cam/detect [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/opt/swatch/swatch/http.py", line 81, in detect_camera_frame
    result: Dict[str, Any] = current_app.image_processor.detect(camera_name, image_url)  # type: ignore[attr-defined]
  File "/opt/swatch/swatch/image.py", line 82, in detect
    if img.size > 0:
AttributeError: 'NoneType' object has no attribute 'size'
```
I think this last one is expected as /media is inaccessible from URLs.

**Comment by NickM-27** [comment]
Thanks, this is helpful, either way those crashes should not be occurring so I will fix those. I will ask the HA devs and see if there is a way for an integration to get the images

**Comment by NickM-27** [comment]
Talked with the devs and unfortunately it seems from the integration I'm only able to get images from the `www` folder which as you pointed out is not secure. Hopefully this will be addressed in a future HA update but for the time being I am going to close this as it doesn't seem I can do anything about it.

**Comment by backslashV** [comment]
> Talked with the devs and unfortunately it seems from the integration I'm only able to get images from the `www` folder which as you pointed out is not secure. Hopefully this will be addressed in a future HA update but for the time being I am going to close this as it doesn't seem I can do anything about it.

Thanks. So how did you get the /media folder to work?

**Comment by NickM-27** [comment]
I haven't gotten it to work for a third party integration, only the first party `Play Media` action is what I was referencing, wondering if that would be possible for an integration to use.
