### ISSUE TITLE
Errors with detect on v2.1.1

### ISSUE THREAD

**Issue by backslashV** [NickM-27/swatch-hass-integration#9]
Hi, when running detect via POST, I see the following in HA logs:
```
Logger: custom_components.swatch
Source: custom_components/swatch/api.py:138
Integration: Swatch ([documentation](https://github.com/NickM-27/swatch-hass-integration), [issues](https://github.com/NickM-27/swatch-hass-integration/issues))
First occurred: 11:46:58 AM (95 occurrences)
Last logged: 11:56:03 AM

Unexpected error fetching swatch data:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.0.109', 5001)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/swatch/api.py", line 98, in api_wrapper
    response = await self._session.get(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.0.109:5001 ssl:default [Connect call failed ('192.168.0.109', 5001)]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 191, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/swatch/__init__.py", line 170, in _async_update_data
    raise exc
  File "/config/custom_components/swatch/__init__.py", line 168, in _async_update_data
    return await self._api.async_get_object_state("all")
  File "/config/custom_components/swatch/api.py", line 76, in async_get_object_state
    await self.api_wrapper(
  File "/config/custom_components/swatch/api.py", line 138, in api_wrapper
    raise SwatchApiClientError from exc
custom_components.swatch.api.SwatchApiClientError
```
Running the swatch service from HA doesn't work either. /colortest/values works fine.

**Comment by NickM-27** [comment]
What does your POST command look like?

**Comment by backslashV** [comment]
```
POST /api/garage_cam/detect HTTP/1.1
Host: <IP>:<port>
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Cache-Control: no-cache
Postman-Token: 73e69fdf-f9eb-082e-6410-eb6e1f702bdf

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="imageUrl"

<image url>
------WebKitFormBoundary7MA4YWxkTrZu0gW--
```

**Comment by NickM-27** [comment]
> ```
> POST /api/garage_cam/detect HTTP/1.1
> Host: <IP>:<port>
> Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
> Cache-Control: no-cache
> Postman-Token: 73e69fdf-f9eb-082e-6410-eb6e1f702bdf
> 
> ------WebKitFormBoundary7MA4YWxkTrZu0gW
> Content-Disposition: form-data; name="imageUrl"
> 
> <image url>
> ------WebKitFormBoundary7MA4YWxkTrZu0gW--
> ```

So a couple things:
1. Is the IP the HAOS IP? Should be fine but just double checking
2. The port is 4500 right?
3. That endpoint expects JSON not form data, I will work to clarify this in the docs.

**Comment by backslashV** [comment]
1. Yes
2. I changed the port to something else in the addon config and the POST request reflects that as well.
3. Ok, when I change it to JSON:
```
POST /api/garage_cam/detect HTTP/1.1
Host: <IP>:<port>
content-type: application/json
Cache-Control: no-cache
Postman-Token: ed72e31d-f097-8eeb-a318-d37e622240a1

{"imageUrl": "url goes here"}
```
I get
```
{
    "message": "<image url> is invalid or does not contain a valid image.",
    "success": false
}
```
however, I am able to open the image url in the browser with no issues.

**Comment by NickM-27** [comment]
Gotcha, that implies some error happened. I'll have to update it so the exception is included in that response.

**Comment by backslashV** [comment]
Thanks. Also, in the addon logs I see
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/opt/swatch/swatch/processing.py", line 28, in run
    self.image_processor.detect(
  File "/opt/swatch/swatch/image.py", line 125, in detect
    result = self.__check_image__(
  File "/opt/swatch/swatch/image.py", line 38, in __check_image__
    now_time = datetime.datetime.now().strftime("%H:%M")
NameError: name 'datetime' is not defined
```

**Comment by NickM-27** [comment]
Okay that's all I needed then, I'll work on an update now

**Comment by NickM-27** [comment]
New addon update is up

**Comment by backslashV** [comment]
That was quick :D. It seems to be working except the /color_playground UI. When I provide the image URL, it doesn't load the image.

**Comment by NickM-27** [comment]
What does the URL look like? Also do you see any errors in the browser? (Inspect element -> console)

I've been using this quite a bit and it's worked so curious what's going on

**Comment by backslashV** [comment]
It's the same URL provided in the config which itself opens just fine when put in the address bar.

From the console:
```
Access to XMLHttpRequest at '<image url here>' from origin '<IP here>' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
Failed to load resource: net::ERR_FAILED
Uncaught TypeError: event.cancelBubble is not a function
    at HTMLDocument.bringBackDefault (new_rightclick.js:87:31)
```

**Comment by NickM-27** [comment]
That's interesting, I wonder if that's an addon issue. Can you try [this url](https://www.istockphoto.com/photo/open-pantone-sample-colors-catalogue-gm609802128-104512785) to see if it works? Will give me some specifics to test with.

**Comment by backslashV** [comment]
That URL is not an image but [this one](https://media.istockphoto.com/photos/open-pantone-sample-colors-catalogue-picture-id609802128?s=612x612) loads fine. Also, 
1) is the picture shown on the /dashboard under zone the cropped picture from the coordinates given in the config?
2) /color_playground is loading the whole image and runs color test on the whole picture as opposed to the cropped one. shouldn't it do the latter? because the RGB values I provided in the config are based on manually cropping the picture and running the /colortest API on it.

**Comment by backslashV** [comment]
FYI, the image is on the HA server, so it has a local IP address.

**Comment by NickM-27** [comment]
> That URL is not an image but [this one](https://media.istockphoto.com/photos/open-pantone-sample-colors-catalogue-picture-id609802128?s=612x612) loads fine. Also, 
> 
> 1) is the picture shown on the /dashboard under zone the cropped picture from the coordinates given in the config?
> 
> 2) /color_playground is loading the whole image and runs color test on the whole picture as opposed to the cropped one. shouldn't it do the latter? because the RGB values I provided in the config are based on manually cropping the picture and running the /colortest API on it.

1. Yes it is cropped from the config. This image is also accessible with /api/<camera_name>/<zone_name>/snapshot.jpg if you want to use that one. 
2. Right now color test has you provide the image directly and doesn't have a camera name so it doesn't crop anything. I haven't worked to improve this as it was just a stopgap until the UI was created.

**Comment by backslashV** [comment]
Thanks. #1 works fine. Not sure why the original image URL isn't working. Also, I noticed the cropped picture is totally different from my manual crop. I used[ this website](https://pixspy.com/) and GIMP to find the coordinates.

**Comment by NickM-27** [comment]
The coordinates structure in python is weird (see the docs). Odds are the website doesn't format it the same

**Comment by NickM-27** [comment]
Also, the UI does crop the images slightly (center crop) so it fills the area of that card, so it may not be an exact representation.

The cropping coordinates are: y:y+h, x:x+w starting in the top left corner

**Comment by backslashV** [comment]
> The cropping coordinates are: y:y+h, x:x+w starting in the top left corner

Yes, that's what I am providing. Are the images under /media/snapshots/<date>/* supposed to be cropped correctly? cause they are also off for me.

**Comment by NickM-27** [comment]
The zone_ and mask_ snapshots follow this cropping. in my testing it works as expected, I would need an example of full image, coords, and the cropped image to see.

**Comment by backslashV** [comment]
So it seems the code is doing what it should. I am not sure why you are providing the coordinates [like this.](https://github.com/NickM-27/swatch/blob/16266a000f0e3dd45ed4c3198ecb72aa55a9e7d8/swatch/image.py#L139)
The expectation is img[y:y+h, x:x+w], so
```
                crop = img[
                    int(coordinates[0]) : int(coordinates[1]),
                    int(coordinates[2]) : int(coordinates[3]),
                ]
```
Also, I am getting a lot of errors following the latest update. By any chance are you testing the updates on HA before release?

From HA logs:
```
This error originated from a custom integration.

Logger: custom_components.swatch
Source: custom_components/swatch/api.py:138
Integration: Swatch (documentation, issues)
First occurred: 4:26:37 PM (7 occurrences)
Last logged: 4:27:07 PM

Unexpected error fetching swatch data:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.0.109', 5001)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/swatch/api.py", line 98, in api_wrapper
    response = await self._session.get(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.0.109:5001 ssl:default [Connect call failed ('192.168.0.109', 5001)]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 191, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/swatch/__init__.py", line 170, in _async_update_data
    raise exc
  File "/config/custom_components/swatch/__init__.py", line 168, in _async_update_data
    return await self._api.async_get_object_state("all")
  File "/config/custom_components/swatch/api.py", line 76, in async_get_object_state
    await self.api_wrapper(
  File "/config/custom_components/swatch/api.py", line 138, in api_wrapper
    raise SwatchApiClientError from exc
custom_components.swatch.api.SwatchApiClientError
```

From the addon logs:
```
Starting SwatchApp
Importing SwatchApp Config
Verified SwatchApp Config
Starting migrations
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3113, in connect
    self._state.set_connection(self._connect())
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3453, in _connect
    conn = sqlite3.connect(self.database, timeout=self._timeout,
sqlite3.OperationalError: unable to open database file
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3175, in execute_sql
    cursor = self.cursor(commit)
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3159, in cursor
    self.connect()
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3112, in connect
    with __exception_wrapper__:
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 2950, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 191, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3113, in connect
    self._state.set_connection(self._connect())
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3453, in _connect
    conn = sqlite3.connect(self.database, timeout=self._timeout,
peewee.OperationalError: unable to open database file
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/swatch/swatch/__main__.py", line 15, in <module>
    swatch_app.start()
  File "/opt/swatch/swatch/app.py", line 98, in start
    self.__init_db__()
  File "/opt/swatch/swatch/app.py", line 49, in __init_db__
    router.run()
  File "/usr/local/lib/python3.10/site-packages/peewee_migrate/router.py", line 201, in run
    diff = self.diff
  File "/usr/local/lib/python3.10/site-packages/peewee_migrate/router.py", line 75, in diff
    done = set(self.done)
  File "/usr/local/lib/python3.10/site-packages/peewee_migrate/router.py", line 70, in done
    return [mm.name for mm in self.model.select().order_by(self.model.id)]
  File "/usr/local/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/usr/local/lib/python3.10/site-packages/peewee_migrate/router.py", line 59, in model
    MigrateHistory.create_table(True)
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 6758, in create_table
    cls._schema.create_all(safe, **options)
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 5861, in create_all
    self.create_table(safe, **table_options)
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 5716, in create_table
    self.database.execute(self._create_table(safe=safe, **options))
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3190, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3174, in execute_sql
    with __exception_wrapper__:
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 2950, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 191, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3175, in execute_sql
    cursor = self.cursor(commit)
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3159, in cursor
    self.connect()
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3112, in connect
    with __exception_wrapper__:
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 2950, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 191, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3113, in connect
    self._state.set_connection(self._connect())
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3453, in _connect
    conn = sqlite3.connect(self.database, timeout=self._timeout,
peewee.OperationalError: unable to open database file
```

**Comment by NickM-27** [comment]
I got confused, I am expecting most people to provide the coordinates as x, y, x+w, y+h which needs to be clarified.

I do test with the integration before releases. I'm not sure why your integration logs at it is set to connect to port 5001? It should be the same port as the webui (5000 inside the container) and nginx routes it to 5001

The addon issue with dbs is known, I haven't been able to test addon as mac has a hard time with VMs but I just found HAs vscode devcontainer for testing addons so should be good to get that fixed and start testing. 

Overall there's a lot of breaking changes as I get going but once it has a good base it'll be a more official and slower release / beta process. I appreciate your help in supporting it in the early days.

**Comment by backslashV** [comment]
Ya, I think it's better to stick with the python format. Even [in the docs ](https://github.com/NickM-27/swatch/blob/main/docs/config.md#:~:text=%23%20NOTE%3A%20The%20order%20of%20the%20coordinates%20are%3A%20y%2C%20y%2Bh%2C%20x%2C%20x%2Bw%20starting%20in%20the%20top%20left%20corner%20as%200%2C%200.)you are specifying it like that.

The integration not connecting is my fault. I changed the port on the addon side but forgot to do the same on the integration end. Thanks.
